/*
Create the following meta data tables.
1. TENANT_LIST
2. DATABASETYPE
3. PRIVILEGE_MAPPING
4. USER_TYPE  ( opitional)
5. SP_LIST 
6. SP_CONTROL
7. PRIVILEGES_MATRIX
8. ROLE_MATRIX
9. SCHEMA_TYPE
10.USER_DATABASE_MAPPING
11.USER_ROLE_MAPPING
*/

USE ROLE SYSADMIN;
USE DATABASE PLATFORM_DB;
USE SCHEMA PROVISION_APP;


CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.TENANT_LIST_SEQ start with 4 increment by 1;
create or replace TABLE PLATFORM_DB.PROVISION_APP.TENANT_LIST (
	TENANT_ID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.TENANT_LIST_SEQ.NEXTVAL,
	TENANT_NAME VARCHAR(100),
	TENANT_ABBREVIATION VARCHAR(50),
	ACTIVE VARCHAR(1),
	MATCH_PATTERN VARCHAR(16777216),
	PRIORITY_NO NUMBER(38,0),
	TAG_JSON VARIANT,
    DATA_PRODUCT_TYPE VARCHAR(100),
	CREATED_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);



CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.DATABASETYPE_SEQ start with 1 increment by 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.DATABASETYPE (
	DATABASETYPEID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.DATABASETYPE_SEQ.NEXTVAL,
	DATABASETYPENAME VARCHAR(16777216)
);



CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING_RUN_SEQ start with 1 increment by 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (
	PRIVILEGEID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING_RUN_SEQ.NEXTVAL COMMENT 'SYSTEM GENERATED SEQUENCE',
	PRIVILEGE VARCHAR(16777216),
	PRIVILEGETYPE VARCHAR(16777216),
	ON_TAG VARCHAR(16777216),
	IN_TAG VARCHAR(16777216)
);


CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.USER_TYPE_SEQ start with 1 increment by 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.USER_TYPE (
	USER_TYPE_ID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.USER_TYPE_SEQ.NEXTVAL,
	USER_TYPE_NAME VARCHAR(300)
);

CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.SP_LIST_SEQ START = 1 INCREMENT = 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.SP_LIST(
    SP_ID NUMBER (38,0) DEFAULT PLATFORM_DB.PROVISION_APP.SP_LIST_SEQ.NEXTVAL COMMENT 'SYSTEM GENERATED SEQUENCE'
   , SP_NAME VARCHAR COMMENT 'STORED PROCEDURE NAME',
   SP_ACTION VARCHAR COMMENT 'STORED PROCEDURE ACTION - CREATE/DROP/MODIFY');

CREATE SEQUENCE IF NOT EXISTS  PLATFORM_DB.PROVISION_APP.SP_CONTROL_SEQ start = 1 increment = 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.SP_CONTROL
    (SP_CONTROL_ID NUMBER (38,0) DEFAULT PLATFORM_DB.PROVISION_APP.SP_CONTROL_SEQ.NEXTVAL COMMENT 'SYSTEM GENERATED SEQUENCE',
     SP_ID NUMBER(38,0) COMMENT 'STORED PROCEDURE ACTION ID',
     ADMIN_ROLE VARCHAR COMMENT 'ADMIN ROLE THAT CAN EXECUTE SP ACTION');



CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.PRIVILEGES_MATRIX (
	ROLETYPE_ID NUMBER(38,0),
	DATABASETYPEID NUMBER(38,0),
	SCHEMA_TYPEID NUMBER(38,0),
	PRIVILEGEID NUMBER(38,0),
	TENANT_ID INTEGER DEFAULT 0
);


CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.ROLE_MATRIX_SEQ start with 1 increment by 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.ROLE_MATRIX (
	ROLETYPE_ID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.ROLE_MATRIX_SEQ.NEXTVAL,
	DATABASETYPEID NUMBER(38,0),
	SCHEMA_TYPEID NUMBER(38,0),
	ROLENAME_TYPE VARCHAR(16777216),
	TENANT_ID INTEGER DEFAULT 0
);



CREATE SEQUENCE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.SCHEMA_TYPE_SEQ start with 1 increment by 1;
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.SCHEMA_TYPE (
	SCHEMA_TYPEID NUMBER(38,0) DEFAULT PLATFORM_DB.PROVISION_APP.SCHEMA_TYPE_SEQ.NEXTVAL,
	SCHEMATYPENAME VARCHAR(16777216),
	SCHEMASHORTNAME VARCHAR(16777216),
	DATABASETYPEID NUMBER(38,0),
	TENANT_ID INTEGER DEFAULT 0
);

--Optional
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.USER_DATABASE_MAPPING (
	USER_TYPE_ID NUMBER(38,0),
	DATABASETYPEID NUMBER(38,0),
	MAPPING_RULES VARCHAR(30),
	TENANT_ID NUMBER(38,0),
	EXT_ROLES_LIST STRING
);
--Optional
CREATE TABLE IF NOT EXISTS PLATFORM_DB.PROVISION_APP.USER_ROLE_MAPPING (
	USER_TYPE_ID NUMBER(38,0),
	ROLE_TYPE_ID NUMBER(38,0),
	TENANT_ID NUMBER(38,0)
);
