/*  SEED DATA 
SP_LIST  contains the list of procs that is used to provision the sf objects in the platform
SP_CONTROL contains the role that is allowed to call the procs
DATABASETYPE - Contains database types like STAGE, CURATED,ENRICHED. All the schema will have to match the database type.
             -  ALL  means that database will contain schema types like STAGE,CURATED,ENRICHED

PLEASE NOTE : SCHEMATYPE will be populated at the time of TENANT setup
*/

USE WAREHOUSE PROVISION_ADHOC_VWH;
INSERT INTO PLATFORM_DB.PROVISION_APP.SP_LIST (SP_NAME, SP_ACTION) VALUES
('DATABASE_WRAPPER', 'CREATE'),
('DATABASE_WRAPPER', 'ALTER'),
('DATABASE_WRAPPER', 'DROP'),
('WAREHOUSE_WRAPPER', 'CREATE'),
('WAREHOUSE_WRAPPER', 'ALTER'),
('WAREHOUSE_WRAPPER', 'DROP'),
('SCHEMA_WRAPPER', 'CREATE'),
('SCHEMA_WRAPPER', 'ALTER'),
('SCHEMA_WRAPPER', 'DROP'),
('ROLE_WRAPPER', 'CREATE'),
('ROLE_WRAPPER', 'ALTER'),
('ROLE_WRAPPER', 'DROP'),
('ROLE_WRAPPER', 'GRANT'),
('ROLE_WRAPPER', 'REVOKE'),
('STORAGE_INTEGRATION_WRAPPER', 'CREATE'),
('STORAGE_INTEGRATION_WRAPPER', 'ALTER'),
('STORAGE_INTEGRATION_WRAPPER', 'DROP'),
('USER_WRAPPER', 'CREATE'),
('USER_WRAPPER', 'ALTER'),
('USER_WRAPPER', 'DROP'),
('RESOURCE_MONITOR_WRAPPER','CREATE'),
('RESOURCE_MONITOR_WRAPPER','ALTER'),
('RESOURCE_MONITOR_WRAPPER','DROP'),
('GRANT_ROLES_TO_ROLE_WRAPPER','GRANT'),
('GRANT_ROLES_TO_ROLE_WRAPPER','REVOKE'),
('GRANT_ROLES_TO_USER_WRAPPER','GRANT'),
('GRANT_ROLES_TO_USER_WRAPPER','REVOKE'),
('LOCK_USER_SQL_PROC','USAGE');

SELECT * FROM PLATFORM_DB.PROVISION_APP.SP_CONTROL;
INSERT INTO PLATFORM_DB.PROVISION_APP.SP_CONTROL(SP_ID, ADMIN_ROLE)
SELECT SP_ID,'SYSADMIN'FROM PLATFORM_DB.PROVISION_APP.SP_LIST;


-- DATABASETYPE
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('STAGE');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('CORE');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('SEMANTIC');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('BUSINESS');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('DATALAKE');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('DATAENG');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('APP');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('POC');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('ENRICHED');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('CURATED');
INSERT INTO PLATFORM_DB.PROVISION_APP.DATABASETYPE (DATABASETYPENAME) VALUES ('ALL');



--DATABASE
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'USAGE','DATABASE','DATABASE' );

--SCHEMA
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'USAGE','SCHEMA','SCHEMA' );

-- TABLES
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE TABLE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','ALL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'DELETE','SCHEMAOBJECT','ALL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'INSERT','SCHEMAOBJECT','ALL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'TRUNCATE','SCHEMAOBJECT','ALL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'UPDATE','SCHEMAOBJECT','ALL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'DELETE','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'INSERT','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'TRUNCATE','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'UPDATE','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE TABLES','SCHEMA' );


-- EXTERNAL TABLES
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE EXTERNAL TABLE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','ALL EXTERNAL TABLES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','FUTURE EXTERNAL TABLES','SCHEMA' );



-- VIEWS
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE VIEW','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','ALL VIEWS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','FUTURE VIEWS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE VIEWS','SCHEMA' );

-- MATERIALIZED VIEWS
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE MATERIALIZED VIEW','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','ALL MATERIALIZED VIEWS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','FUTURE MATERIALIZED VIEWS','SCHEMA' );


-- FILE FORMAT
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE FILE FORMAT','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'USAGE','SCHEMAOBJECT','ALL FILE FORMATS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'USAGE','SCHEMAOBJECT','FUTURE FILE FORMATS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE FILE FORMATS','SCHEMA' );

-- CREATE SEQUENCE
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE SEQUENCE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'USAGE','SCHEMAOBJECT','ALL SEQUENCES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'USAGE','SCHEMAOBJECT','FUTURE SEQUENCES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE SEQUENCES','SCHEMA' );


-- PROCEDURES
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE PROCEDURE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG,IN_TAG  ) VALUES ( 'USAGE','SCHEMA','ALL PROCEDURES' ,'SCHEMA');
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG,IN_TAG  ) VALUES ( 'USAGE','SCHEMA','FUTURE PROCEDURES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG,IN_TAG  ) VALUES ( 'OWNERSHIP','SCHEMA','FUTURE PROCEDURES','SCHEMA' );


--FUNCTIONS
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE FUNCTION','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG,IN_TAG ) VALUES ( 'USAGE','SCHEMA','ALL FUNCTIONS' ,'SCHEMA');
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG,IN_TAG ) VALUES ( 'USAGE','SCHEMA','FUTURE FUNCTIONS' ,'SCHEMA');
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG  ) VALUES ( 'OWNERSHIP','SCHEMA','FUTURE FUNCTIONS','SCHEMA' );


-- EXTERNAL FUNCTIONS
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE EXTERNAL FUNCTION','SCHEMA','SCHEMA' );

-- STAGE
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE STAGE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG ) VALUES ( 'READ','SCHEMA','ALL STAGES' ,'SCHEMA');
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG ) VALUES ( 'READ','SCHEMA','FUTURE STAGES' ,'SCHEMA');
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG ) VALUES ( 'WRITE','SCHEMA','ALL STAGES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG ) VALUES ( 'WRITE','SCHEMA','FUTURE STAGES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG, IN_TAG ) VALUES ( 'OWNERSHIP','SCHEMA','FUTURE STAGES','SCHEMA' );


-- TASK
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE TASK','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'MONITOR','SCHEMAOBJECT','ALL TASKS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'MONITOR','SCHEMAOBJECT','FUTURE TASKS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OPERATE','SCHEMAOBJECT','ALL TASKS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OPERATE','SCHEMAOBJECT','FUTURE TASKS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE TASKS','SCHEMA' );


-- PIPE
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE PIPE','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'MONITOR','SCHEMAOBJECT','FUTURE PIPES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OPERATE','SCHEMAOBJECT','FUTURE PIPES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE PIPES','SCHEMA' );

--Bulk grant is not allowed for pipes
--INSERT INTO PLATFORM_DB.PROVISION.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'MONITOR','SCHEMAOBJECT','ALL PIPES','SCHEMA' );
--INSERT INTO PLATFORM_DB.PROVISION.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OPERATE','SCHEMAOBJECT','ALL PIPES','SCHEMA' );


-- STREAM
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE STREAM','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','ALL STREAMS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'SELECT','SCHEMAOBJECT','FUTURE STREAMS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE STREAMS','SCHEMA' );


-- MASKING POLICY
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE MASKING POLICY','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'APPLY','SCHEMAOBJECT','ALL MASKING POLICIES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'APPLY','SCHEMAOBJECT','FUTURE MASKING POLICIES','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE MASKING POLICIES','SCHEMA' );


-- TAGS
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ) VALUES ( 'CREATE TAG','SCHEMA','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'APPLY','SCHEMAOBJECT','ALL TAGS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'APPLY','SCHEMAOBJECT','FUTURE TAGS','SCHEMA' );
INSERT INTO PLATFORM_DB.PROVISION_APP.PRIVILEGE_MAPPING (PRIVILEGE, PRIVILEGETYPE, ON_TAG ,IN_TAG) VALUES ( 'OWNERSHIP','SCHEMAOBJECT','FUTURE TAGS','SCHEMA' );
 