USE ROLE SYSADMIN;
CREATE or REPLACE PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.ADD_METADATA_FOR_TENANT (
                                            P_TENANT_ABBREVIATION VARCHAR,
                                            V_SCHEMA_OBJECT_TYPE VARCHAR,
                                            V_DATABASETYPENAME VARCHAR
) 

RETURNS ARRAY  NOT NULL
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
DECLARE 

    TENANT VARCHAR DEFAULT '';
    JOB_NAME VARCHAR DEFAULT '';
    JOB_ACTION VARCHAR DEFAULT '';
    IS_ERROR VARCHAR DEFAULT '0';
    JOB_LOG_DESCRIPTION VARCHAR DEFAULT '';
    SCHEMA_EXCEPTION EXCEPTION;
    LOG VARIANT DEFAULT '';

    META_SQL VARCHAR DEFAULT '';
    


--SET V_TENANT_ABBREVIATION = 'KP_WIS';
--SET V_SCHEMA_OBJECT_TYPE = 'STAGE';  ---  THIS NEEDS TO BE REPLACE WITH SCHEMA TYPE STAGE, ENRICHED , CURATED 
--SET V_DATABASETYPENAME = 'ALL';  -- ALL means database as product 
--SET V_SCHEMASHORTNAME = '';


END;
$$;
