USE ROLE SYSADMIN  ;

CREATE OR REPLACE PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.ALTER_SCHEMA_SQL_PROC (
                DATABASENAME_PARAMETER  VARCHAR,
                SCHEMANAME_PARAMETER    VARCHAR,
                RETENTION_PARAMETER  VARCHAR,
                COMMENT_PARAMETER VARCHAR,
                MANAGED_ACCESS_PARAMETER VARCHAR,
                TENANT_NAME_PARAMETER VARCHAR 
                )

RETURNS ARRAY NOT NULL
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
   TENANT VARCHAR DEFAULT '';
   JOB_NAME VARCHAR DEFAULT '';
   JOB_ACTION VARCHAR DEFAULT '';
   IS_ERROR VARCHAR DEFAULT '0';
   JOB_LOG_DESCRIPTION VARCHAR DEFAULT '';
   SCHEMA_EXCEPTION EXCEPTION;

   LOG VARIANT DEFAULT '';

    SCHEMA_SQL VARCHAR DEFAULT '';
    SCHEMA_TYPE  VARCHAR DEFAULT '';

BEGIN
    IS_ERROR := '0';
    TENANT := TENANT_NAME_PARAMETER;

  IF (DATABASENAME_PARAMETER IS NULL OR TRIM(DATABASENAME_PARAMETER) = '' OR SCHEMANAME_PARAMETER IS NULL OR TRIM(SCHEMANAME_PARAMETER) = ''OR COMMENT_PARAMETER IS NULL OR TRIM(COMMENT_PARAMETER) = '') THEN
            RAISE SCHEMA_EXCEPTION;
    END IF;
    LET SCHEMA_ALTER_SQL VARCHAR :='';
    IF ( NULLIF(TRIM(RETENTION_PARAMETER ), '') IS NOT NULL) THEN
        SCHEMA_ALTER_SQL:= SCHEMA_ALTER_SQL || ' DATA_RETENTION_TIME_IN_DAYS='||RETENTION_PARAMETER ;
    END IF;

    IF (NULLIF(TRIM(COMMENT_PARAMETER), '') IS NOT NULL) THEN
        SCHEMA_ALTER_SQL:= SCHEMA_ALTER_SQL || ' COMMENT=''' ||COMMENT_PARAMETER ||'''' ;
    END IF;

    SCHEMA_ALTER_SQL := ' ALTER SCHEMA '|| DATABASENAME_PARAMETER || '.' || SCHEMANAME_PARAMETER || ' SET '||SCHEMA_ALTER_SQL || ';';

    EXECUTE IMMEDIATE SCHEMA_ALTER_SQL;
    
    JOB_LOG_DESCRIPTION := ' -- SCHEMA ALTERED: ' || DATABASENAME_PARAMETER || '.' || SCHEMANAME_PARAMETER || ' COMMENT: ' || COMMENT_PARAMETER || ' SCHEMA_ALTER_SQL : \n' || SCHEMA_ALTER_SQL;

    IF (NULLIF(TRIM(MANAGED_ACCESS_PARAMETER), '') IS NOT NULL) THEN
        SCHEMA_ALTER_SQL:= ' ALTER SCHEMA ' || DATABASENAME_PARAMETER || '.' || SCHEMANAME_PARAMETER || ' ENABLE MANAGED ACCESS' || ';';
    END IF;
    
    EXECUTE IMMEDIATE SCHEMA_ALTER_SQL;

    JOB_LOG_DESCRIPTION := JOB_LOG_DESCRIPTION || '\n' || SCHEMA_ALTER_SQL;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

EXCEPTION

  
  WHEN SCHEMA_EXCEPTION  THEN
      IS_ERROR := '1';
      JOB_LOG_DESCRIPTION := 'ERROR: INVALID PARAMETERS' ||  ' COMMENT: ' || COMMENT_PARAMETER;
      RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

  WHEN OTHER THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'SQLCODE:' || SQLCODE || ' SQLERRM:' || SQLERRM || ' SQLSTATE:' ||SQLSTATE;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;
END;
$$;

