USE ROLE SYSADMIN;
CREATE or REPLACE PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.ALTER_DATABASE_SQL_PROC (
                                            DB_NAME VARCHAR,
                                            DB_TAG VARCHAR,
                                            COMMENT VARCHAR,
                                            RETENTION_PARAMETER VARCHAR,
                                            TENANT_NAME_PARAMETER VARCHAR
) 

RETURNS ARRAY  NOT NULL
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
 DECLARE
   TENANT VARCHAR DEFAULT '';
   JOB_NAME VARCHAR DEFAULT '';
   JOB_ACTION VARCHAR DEFAULT '';
   IS_ERROR VARCHAR DEFAULT '';
   JOB_LOG_DESCRIPTION VARCHAR DEFAULT '';
   DB_EXCEPTION_PARAMETER  EXCEPTION;
   DB_ALTER_SQL VARCHAR DEFAULT '';

   LOG VARIANT DEFAULT '';
BEGIN
    IS_ERROR := '0';
    
    TENANT := TENANT_NAME_PARAMETER;


    IF (DB_NAME IS NULL OR TRIM(DB_NAME) = '' OR (DB_TAG IS NULL AND COMMENT IS NULL AND RETENTION_PARAMETER IS NULL) ) THEN
            RAISE DB_EXCEPTION_PARAMETER;
    END IF;
    DB_ALTER_SQL :='';
    IF ( NULLIF(TRIM(RETENTION_PARAMETER ), '') IS NOT NULL) THEN
        DB_ALTER_SQL:= DB_ALTER_SQL || ' DATA_RETENTION_TIME_IN_DAYS='||RETENTION_PARAMETER ;
    END IF;
    IF (NULLIF(TRIM(DB_TAG), '') IS NOT NULL) THEN
        DB_ALTER_SQL:= DB_ALTER_SQL || ' COMMENT=''' ||DB_TAG ||'''' ;
    END IF;

    DB_ALTER_SQL := 'ALTER DATABASE '||DB_NAME || ' SET '||DB_ALTER_SQL;

    EXECUTE IMMEDIATE DB_ALTER_SQL;
    
    JOB_LOG_DESCRIPTION := '-- DATABASE ALTERED: ' || DB_NAME || ' COMMENT: ' || COMMENT || ' DB_ALTER_SQL: \n' || DB_ALTER_SQL;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

EXCEPTION

  
  WHEN DB_EXCEPTION_PARAMETER  THEN
      IS_ERROR := '1';
      JOB_LOG_DESCRIPTION := 'ERROR: INVALID PARAMETERS' || DB_NAME || ' COMMENT: ' || COMMENT;
      RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

  WHEN OTHER THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'SQLCODE:' || SQLCODE || ' SQLERRM:' || SQLERRM || ' SQLSTATE:' ||SQLSTATE;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

END;
$$;
