USE ROLE SECURITYADMIN;

DROP procedure if exists PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC (VARCHAR,VARCHAR,VARCHAR);


USE ROLE SYSADMIN ;
CREATE or REPLACE PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC (ROLE_NAME VARCHAR,WH_NAME VARCHAR, TENANT_NAME_PARAMETER VARCHAR)
RETURNS ARRAY  NOT NULL
LANGUAGE SQL
EXECUTE AS   OWNER
AS
$$
DECLARE
   TENANT VARCHAR DEFAULT '';
   JOB_NAME VARCHAR DEFAULT '';
   JOB_ACTION VARCHAR DEFAULT '';
   IS_ERROR VARCHAR DEFAULT '0';
   ROLE_NAME_EXCEPTION  EXCEPTION;
   ROLE_GRANT_SQL VARCHAR DEFAULT '';
   JOB_LOG_DESCRIPTION VARCHAR DEFAULT '';

BEGIN
	JOB_NAME := 'GRANT_USAGE_WAREHOUSE';
   -- JOB_ACTION := ACTION;
    IS_ERROR := '0';
    TENANT := TENANT_NAME_PARAMETER;
    
    IF (  ENDSWITH ( ROLE_NAME,'_ROLE') AND STARTSWITH (ROLE_NAME,TENANT)) THEN
    ROLE_GRANT_SQL := ' GRANT USAGE ON WAREHOUSE ' || WH_NAME  ||' TO ROLE ' || ROLE_NAME || ';';
    EXECUTE IMMEDIATE ROLE_GRANT_SQL;
    JOB_LOG_DESCRIPTION := '-- ROLE GRANTED USAGE '|| ROLE_NAME || ' ROLE_GRANT_SQL: \n' || ROLE_GRANT_SQL || '\n';
  
  ELSE
    RAISE ROLE_NAME_EXCEPTION;
  END IF ;

    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

  

EXCEPTION

  WHEN ROLE_NAME_EXCEPTION  THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'ERROR: ROLE NAME NOT IN RIGHT FORMAT {WAREHOUSE}_ROLE' ; ;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

  WHEN OTHER THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'SQLCODE:' || SQLCODE || ' SQLERRM:' || SQLERRM || ' SQLSTATE:' ||SQLSTATE;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

END;

$$;

grant ownership on procedure PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC(VARCHAR,VARCHAR,VARCHAR) to ROLE SECURITYADMIN;
USE ROLE SECURITYADMIN;

grant USAGE on procedure PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC (VARCHAR,VARCHAR,VARCHAR) to ROLE SYSADMIN;


-- -- to Drop
-- grant ownership on procedure PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC(VARCHAR,VARCHAR,VARCHAR) to ROLE SYSADMIN REVOKE CURRENT GRANTS;
-- USE ROLE SYSADMIN;
-- DROP PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.GRANT_USAGE_WAREHOUSE_SQL_PROC(VARCHAR,VARCHAR,VARCHAR) ;
