
USE ROLE SECURITYADMIN;
--DROP PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC (VARCHAR);
drop procedure if exists PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC (VARCHAR);

USE ROLE SYSADMIN;

CREATE or REPLACE PROCEDURE  PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC(GRANT_NAME VARCHAR)

--RETURNS VARIANT  NOT NULL
  RETURNS ARRAY  NOT NULL
LANGUAGE SQL
EXECUTE AS   OWNER
AS
$$
DECLARE

    TENANT VARCHAR DEFAULT '';
    JOB_NAME VARCHAR DEFAULT '';
    JOB_ACTION VARCHAR DEFAULT '';
    IS_ERROR VARCHAR DEFAULT '0';
    JOB_LOG_DESCRIPTION VARCHAR DEFAULT '';
    ROLE_NAME_EXCEPTION EXCEPTION;
    LOG VARIANT DEFAULT '';

BEGIN

    IS_ERROR := '0';
  
    IF (CONTAINS(GRANT_NAME, '_ROLE')) THEN
    EXECUTE IMMEDIATE GRANT_NAME;
    JOB_LOG_DESCRIPTION := '-- GRANT EXECUTED: \n'||GRANT_NAME;

    --RETURN OBJECT_CONSTRUCT('TENANT',:TENANT,'JOB_NAME',:JOB_NAME, 'JOB_LOG_DESCRIPTION',:JOB_LOG_DESCRIPTION, 'IS_ERROR', :IS_ERROR, 'ACTION', :JOB_ACTION);
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

  ELSE
    RAISE ROLE_NAME_EXCEPTION;
  END IF ;

EXCEPTION

  WHEN ROLE_NAME_EXCEPTION  THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'ERROR: ROLE NAME NOT IN RIGHT FORMAT' ; ;
    --RETURN OBJECT_CONSTRUCT('TENANT',:TENANT,'JOB_NAME',:JOB_NAME, 'JOB_LOG_DESCRIPTION',:JOB_LOG_DESCRIPTION, 'IS_ERROR', :IS_ERROR, 'ACTION', :JOB_ACTION)  ;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;


  WHEN OTHER THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'ERROR';
    --JOB_LOG_DESCRIPTION := 'SQLCODE:' || SQLCODE || ' SQLERRM:' || SQLERRM || ' SQLSTATE:' ||SQLSTATE;
    --RETURN OBJECT_CONSTRUCT('TENANT',:TENANT,'JOB_NAME',:JOB_NAME, 'JOB_LOG_DESCRIPTION',:JOB_LOG_DESCRIPTION, 'IS_ERROR', :IS_ERROR, 'ACTION', :JOB_ACTION)  ;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

END;
$$;





grant ownership on procedure PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC (VARCHAR) to ROLE SECURITYADMIN;

USE ROLE SECURITYADMIN;
--DROP PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC (VARCHAR);
grant USAGE on procedure PLATFORM_DB.PROVISION_ROUTINE.GRANT_ROLE_SQL_PROC (VARCHAR) to ROLE SYSADMIN;

