
USE ROLE SECURITYADMIN;
--DROP PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC (VARCHAR,VARCHAR,VARCHAR,VARCHAR);
drop procedure if exists PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC (VARCHAR,VARCHAR,VARCHAR,VARCHAR);

USE ROLE SYSADMIN;

CREATE or REPLACE PROCEDURE  PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC(
        P_USER_NAME VARCHAR,
        P_RSA_PUBLIC_KEY VARCHAR,
        P_RSA_PUBLIC_KEY_2 VARCHAR,
        P_TENANT_NAME VARCHAR
        )

RETURNS ARRAY NOT NULL
LANGUAGE SQL
EXECUTE AS   OWNER
AS
$$
DECLARE

    TENANT VARCHAR DEFAULT '';
    JOB_NAME VARCHAR DEFAULT '';
    JOB_ACTION VARCHAR DEFAULT '';
    IS_ERROR VARCHAR DEFAULT '0';
    JOB_LOG_DESCRIPTION VARCHAR;
    TENANT_EXCEPTION_PARAMETER EXCEPTION;
    ROLE_NAME_EXCEPTION EXCEPTION;
    USER_SQL VARCHAR DEFAULT '';

    LOG VARIANT DEFAULT '';

BEGIN

    IS_ERROR := '0';
    TENANT := P_TENANT_NAME;
  
    USER_SQL :=  'ALTER USER ' || P_USER_NAME || ' SET RSA_PUBLIC_KEY = '|| P_RSA_PUBLIC_KEY || ' RSA_PUBLIC_KEY_2 = '|| P_RSA_PUBLIC_KEY_2 || ' ;';
    EXECUTE IMMEDIATE USER_SQL;
    JOB_LOG_DESCRIPTION := '-- PUBLIC KEY CHANGED FOR USER: '|| P_USER_NAME;

    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

EXCEPTION
  WHEN OTHER THEN
    IS_ERROR := '1';
    JOB_LOG_DESCRIPTION := 'SQLCODE:' || SQLCODE || ' SQLERRM:' || SQLERRM || ' SQLSTATE:' ||SQLSTATE;
    RETURN ARRAY_CONSTRUCT(:IS_ERROR,:JOB_LOG_DESCRIPTION)  ;

END;
$$;


grant ownership on procedure PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC (VARCHAR,VARCHAR,VARCHAR,VARCHAR) to ROLE SECURITYADMIN;

USE ROLE SECURITYADMIN;
--DROP PROCEDURE PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC (VARCHAR,VARCHAR,VARCHAR,VARCHAR);
grant USAGE on procedure PLATFORM_DB.PROVISION_ROUTINE.ROTATE_USER_KEYPAIR_SQL_PROC (VARCHAR,VARCHAR,VARCHAR,VARCHAR) to ROLE SYSADMIN;
